### ISSUE TITLE
Add silent mode

### ISSUE THREAD

**Issue by HoelscherC** [mkroening/edu-sync#4]
When using a script to execute edu-sync the terminal pops up to show the output. It would be nice if you could change the behavior of that so that nothing is printed if no error occurs or at all.

**Comment by mkroening** [comment]
As we discussed, the fact that the terminal opens is caused by your setup and would not change if edu-sync did not produce any output.

If you run any CLI app manually, a terminal will open, as far as I know (maybe your desktop environment has a setting for that though). You might be interested in running edu-sync as a service though. I opened an issue to provide an example: https://github.com/mkroening/edu-sync/issues/5

Side note: I am not sure if you are aware, but `edu-sync-cli sync` has a `--no-confirm` flag for running in scripts. See `edu-sync-cli sync --help`.

If you are still interested in a silent mode for less verbose output, feel free to reopen this issue though. :)
